# version: "3"

# services:
#   # Database
#   bdd:
#     container_name: bdd
#     image: mysql
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: ecf3db
#       MYSQL_PASSWORD: password
#     networks:
#       - mysql-phpmyadmin

#   # phpmyadmin
#   phpmyadmin:
#     depends_on:
#       - bdd
#     image: phpmyadmin
#     restart: always
#     ports:
#       - "8090:80"
#     environment:
#       PMA_HOST: bdd
#     networks:
#       - mysql-phpmyadmin

#   # Authentication Service
 
#   authservice:
#     container_name: authservice
#     ports:
#       - "8082:8080"
#     build: 
#       context: ./server/authentication-service
#       dockerfile: Dockerfile
#     depends_on:
#       - bdd
#     environment:
#       PORT: 8080
#       ACTIVE_PROFILE: default
#       DB_HOST: bdd
#       DB_PORT: 3306
#       DB_SCHEMA: ecf3db
#       DB_USER: root
#       DB_PASS: password
#     networks:
#       - mysql-phpmyadmin

#   # Common Data Service
    
#   dataservice:
#     container_name: dataservice
#     ports:
#       - "8083:8080"
#     build:
#       context: ./server/common-data-service
#       dockerfile: Dockerfile
#     depends_on:
#       - bdd
#     environment:
#       REDIS_HOST: "localhost"
#       REDIS_PORT: "6379"
#       REDIS_PASSWORD: "yourpassword"
#       PORT: 8080
#       SPRING_PROFILES_ACTIVE: dev
#       DB_HOST: bdd
#       DB_PORT: 3306
#       DB_SCHEMA: ecf3db
#       DB_USER: root
#       DB_PASS: password
#     networks:
#       - mysql-phpmyadmin

      

#   # Payment Service

#   payservice:
#     container_name: payservice
#     ports:
#       - "8084:8080"
#     build:
#       context: ./server/payment-service
#       dockerfile: Dockerfile
#     depends_on:
#       - bdd
#     environment:
#       PORT: 8080
#       ACTIVE_PROFILE: default
#       DB_HOST: bdd
#       DB_PORT: 3306
#       DB_SCHEMA: ecf3db
#       DB_USER: root
#       DB_PASS: password
#     networks:
#       - mysql-phpmyadmin

#   # Frontend
#   node:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     container_name: thisappcont
#     ports:
#       - "80:80"
#     depends_on:
#       - authservice
#       - dataservice
#       - payservice
#     networks:
#       - mysql-phpmyadmin

# networks:
#   mysql-phpmyadmin:
#     driver: bridge

# volumes:
#   db_data:



# # docker-compose up -d

# # docker-compose down

version: "3.8"

services:
  # Database
  bdd:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecf3db
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - bdd
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: bdd
    networks:
      - mysql-phpmyadmin

  # Authentication Service
  authservice:
    container_name: authservice
    ports:
      - "8082:8080"
    build: 
      context: ./server/authentication-service
      dockerfile: Dockerfile
    depends_on:
      - bdd
    environment:
      PORT: 8080
      ACTIVE_PROFILE: default
      DB_HOST: bdd
      DB_PORT: 3306
      DB_SCHEMA: ecf3db
      DB_USER: root
      DB_PASS: password
    networks:
      - mysql-phpmyadmin

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mysql-phpmyadmin

  # Common Data Service
  dataservice:
    container_name: dataservice
    ports:
      - "8083:8080"
    build:
      context: ./server/common-data-service
      dockerfile: Dockerfile
    depends_on:
      - bdd
      - redis
    environment:
      REDIS_HOST: "dataservice_redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "password"
      PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: bdd
      DB_PORT: 3306
      DB_SCHEMA: ecf3db
      DB_USER: root
      DB_PASS: password
    networks:
      - mysql-phpmyadmin

  # Payment Service
  payservice:
    container_name: payservice
    ports:
      - "8084:8080"
    build:
      context: ./server/payment-service
      dockerfile: Dockerfile
    depends_on:
      - bdd
    environment:
      PORT: 8080
      ACTIVE_PROFILE: default
      DB_HOST: bdd
      DB_PORT: 3306
      DB_SCHEMA: ecf3db
      DB_USER: root
      DB_PASS: password
    networks:
      - mysql-phpmyadmin

  # Frontend
  node:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: thisappcont
    ports:
      - "80:80"
    depends_on:
      - authservice
      - dataservice
      - payservice
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data:



